# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fb_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
