# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 06:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_fb_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date and Time'),
        ),
    ]
