# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 23:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160309_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='End Date / Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Start Date / Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fb_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook Event URL'),
        ),
    ]
