# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160309_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_address',
            field=models.CharField(default='here', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date_time',
            field=models.DateTimeField(verbose_name='End Date / Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date_time',
            field=models.DateTimeField(verbose_name='Start Date / Time'),
        ),
    ]
