# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160419_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Gainesville', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(default='FL', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='zip_code',
            field=models.IntegerField(default=32611),
            preserve_default=False,
        ),
    ]
